default_config:

logger:
  default: info
  logs:
    custom_components.elasticsearch: debug

 elasticsearch:
   url: https://localhost:9200
   verify_ssl: false
   username: hass
   password: changeme
